package:
  name: symengine-python
  version: 0.9.2
source:
  sha256: 9da048692d741bb001d9947a0e2bdf8909600cb4e6f3b9273d518cf93300955d
  url: https://github.com/symengine/symengine.py/releases/download/v0.9.2/symengine.py-0.9.2.tar.gz
build:
  ldflags: |
    -L$(NUMPY_LIB)
requirements:
  run:
    - gmp
    - setuptools
    - numpy
    - symengine
test:
  imports:
    - symengine
