name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: main-${{ github.head_ref }}

jobs:
  build-core:
    runs-on: ubuntu-latest
    env:
      EMSDK_NUM_CORES: 3
      EMCC_CORES: 3
      PYODIDE_JOBS: 3
      CCACHE_DIR: /tmp/ccache

    steps:
      - uses: actions/checkout@v2
        with:
          repository: pyodide/pyodide
          ref: a95a27e754e61749d7069421387e916bd8edbd7e
      - uses: actions/checkout@v2
        with:
          path: _overlay
      - run: cp -r _overlay/* .

      - name: Cache ccache output
        uses: actions/cache@v2
        with:
          path: |
            /tmp/ccache
          key: ${{ hashFiles('Makefile.envs') }}-v20211025-

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyodide-env
          python-version: 3.10.2
          channels: conda-forge

      - name: Check Python versions
        shell: bash -l {0}
        run: |
          python --version
          which python
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          sudo apt install -y build-essential git
          conda install -y nodejs ccache f2c pkg-config swig make patch pkg-config texinfo autoconf automake libtool
          pip install -r requirements.txt
      - name: Build emsdk
        shell: bash -l {0}
        run: |
          which ccache
          ccache -z
          make -C emsdk
          ccache -s
      - name: Build Cpython
        shell: bash -l {0}
        run: |
          # This is necessary to use the ccache from emsdk
          source pyodide_env.sh
          which ccache
          ccache -z
          make -C cpython
          ccache -s
      - name: build Pyodide distribution
        shell: bash -l {0}
        run: |
          # This is necessary to use the ccache from emsdk
          source pyodide_env.sh
          ccache -z
          PYODIDE_PACKAGES="core,pycalphad" make
          ccache -s
      - name: check-size
        run: ls -lh dist/

      - name: Store artifacts build
        uses: actions/upload-artifact@v2
        with:
          name: mgf-pyodide
          path: ./dist/
          retention-days: 60